### ISSUE TITLE
Content disappears when order is changed

### ISSUE THREAD

**Issue by sweebee** [mohamedsabil83/filament-forms-tinyeditor#37]
Like #23 this issue still persists. When re-ordering or removing a field from a repeater the content is gone.

**Comment by mohamedsabil83** [comment]
Can you provide an example code to reimplement the issue? It's good practice btw.

**Comment by rjvandoesburg** [comment]
I had a similar issue a while back, i solved it by using
`tinymce.execCommand('mceRemoveEditor', false, editor.id);` and `tinymce.execCommand('mceAddEditor', false, editor.id);`

Because when you move an active instance the editor gets messed up. 
When you start adding/deleting a block or start reordering the editors should be disabled.
When the item was added/deleted or reordering has ended the editors should be enabled.

I am currently looking at it for a bit, but i wasn't using livewire back then so in combination with the existing events this seems quite troublesome.

@mohamedsabil83 This issue is reproducable by creating a resource and using the following:
```
use Filament\Forms\Components\Builder;
use Filament\Forms\Components\Builder\Block;
use Mohamedsabil83\FilamentFormsTinyeditor\Components\TinyEditor;

Builder::make('blocks')
        ->schema([
            Block::make('text')
                ->schema([
                    TinyEditor::make('content')
                ]),
        ]),

```

**Comment by oz-hjx210** [comment]
When I drag a block that contains TinyEditor inside the Builder\Block , TinyEditor loses its content an focus and I am unable to edit it.

please hlep

**Comment by oz-hjx210** [comment]
@rjvandoesburg  
where can i use  this code 
tinymce.execCommand('mceRemoveEditor', false, editor.id); and tinymce.execCommand('mceAddEditor', false, editor.id);

**Comment by rjvandoesburg** [comment]
Not sure, but it should be called on the drag event and then the second one when the dragging stops

**Comment by oz-hjx210** [comment]
@rjvandoesburg  can you show you DEMO code  for me ,I doun't know  any more  to  fix this issue. thanks very much

**Comment by alonzrihan** [comment]
I'm using the latest version of tinymce (6.6.2) and this issue still happens, we have a list of editors that can be reorder and when it does the content disappears

**Comment by alonzrihan** [comment]
I'm using the latest version of tinymce (6.6.2) and this issue still happens, we have a list of editor that can be reorder and when it does the content disappears

**Comment by mohamedsabil83** [comment]
This package is built on top of TinyMCE version 5

**Comment by alonzrihan** [comment]
What package? tinymce-react ?

**Comment by mohamedsabil83** [comment]
**Filament Forms TinyEditor** built for **TinyMce 5**

**Comment by alonzrihan** [comment]
my bad didn't see this thread is regarding Filament, I'm using tinymce-react, I'll open a new ticket
